---
# tasks file for desktop
- name: install software
  package:
    name: "{{ desktop_software }}"
    state: present
  register: desktop_install_software
  until: desktop_install_software is succeeded
  retries: 3
  when:
    - desktop_installation_method == "package"

- name: install software manually
  command: dnf groupinstall --allowerasing --assumeyes "{{ item }}"
  loop: "{{ desktop_software }}"
  register: desktop_install_software_manually
  until: desktop_install_software_manually is succeeded
  retries: 3
  changed_when: "'Installed:' in desktop_install_software_manually.stdout"
  when:
    - desktop_installation_method == "manual"
