---
# tasks file for desktop
- name: install software
  package:
    name: "{{ item.name }}"
    state: present
  loop: "{{ desktop_software }}"
  loop_control:
    label: "{{ item.name }}"
  register: desktop_install_software
  until: desktop_install_software is succeeded
  retries: 3
  when:
    - item.module is not defined or
      item.module != "command"

# Work around the missing parameter `allowerasing` for `yum`.
- name: install software manually
  command: "{{ ansible_pkg_mgr }} groupinstall --allowerasing --assumeyes '{{ item.name }}'"
  args:
    warn: no
  loop: "{{ desktop_software }}"
  loop_control:
    label: "{{ item.name }}"
  register: desktop_install_software_manually
  until: desktop_install_software_manually is succeeded
  retries: 3
  changed_when: "'Installed:' in desktop_install_software_manually.stdout"
  when:
    - ansible_pkg_mgr in ["dnf", "yum"]
    - item.module is defined
    - item.module == "command"
