---
# tasks file for desktop
- name: install software
  package:
    name: "{{ desktop_software }}"
    state: present
  register: desktop_install_software
  until: desktop_install_software is succeeded
  retries: 3
